### ISSUE TITLE
[6.4.3 regression] Installs pkgconfig into the root

### ISSUE THREAD

**Issue by yurivict** [Taywee/args#110]
The list of files is now:
```
/pkgconfig/args.pc
include/args.hxx
lib/cmake/args/args-config-version.cmake
lib/cmake/args/args-config.cmake
```
```/pkgconfig/args.pc``` file should be at ```/usr/local/pkgconfig/args.pc```.

**Comment by Taywee** [comment]
Interesting.  I didn't catch this because I specified a different `CMAKE_INSTALL_PREFIX` directory for it, which still installed that file under `${CMAKE_INSTALL_PREFIX}/lib64/pkgconfig/args.pc`.  When I leave out CMAKE_INSTALL_PREFIX, it indeed installs it under `/pkgconfig`.  I'll get right on that.  Thanks for the heads up.

**Comment by Taywee** [comment]
6.4.4 fixes this.  Thanks again for the follow-up report.

**Comment by yurivict** [comment]
Thanks for fixing it!
