### ISSUE TITLE
Detect console/terminal width

### ISSUE THREAD

**Issue by cbielow** [Taywee/args#112]
Currently the output on the console seems to assume a width of 80
https://github.com/Taywee/args/blame/master/args.hxx#L609

Would you be interested in auto-detecting code? We have that code in OpenMS (https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/APPLICATIONS/ConsoleUtils.cpp#L64) and its pretty light-weight (, but requires inclusion of <windows.h> on Windows -- which may be a problem in a header-only library :) ).

**Comment by Taywee** [comment]
80 is the default, but it can be overridden via [the `helpParams` public field of `ArgumentParser`](https://github.com/Taywee/args/blame/master/args.hxx#L2823-L2826).

I don't think I want to integrate auto-detecting code into the library.  I want to stick to stdlib dependencies only, and basically ignore all platform concerns as much as I can get away with (particularly because somebody could feasibly use this in a bespoke environment without any sort of real terminal).  User code can easily detect width itself if appropriate and set `helpParams.width` accordingly.

**Comment by cbielow** [comment]
I see.
I'll just implement it in my app.
Thanks!
