### ISSUE TITLE
Setting default value for arguments

### ISSUE THREAD

**Issue by darealshinji** [Taywee/args#119]
There are cases where I want a default value to be set if nothing was specified through command line. For example whether the user specified a temporary directory path:
``` C++
args::ValueFlag<std::string> a_temp(args, "PATH", "temporary directory", {"temp"});
std::string s_temp = a_temp ? args::get(a_temp) : "/tmp";
std::cout << "temporary directory: " << s_temp << std::endl;
```

I would prefer to somehow set an optional default value at initialization of `a_temp`:
``` C++
args::ValueFlag<std::string> a_temp(args, "PATH", "temporary directory", {"temp"}, "/tmp");
std::cout << "temporary directory: " << args::get(a_temp) << std::endl;
```

**Comment by darealshinji** [comment]
Nevermind, I should have checked the full API doc first. The readme file didn't mention it's possible. The readme also doesn't tell that you can use the member function `Get()` instead of `args::get()`.

**Comment by Taywee** [comment]
No worries. It's easy to miss these things, because of the way the documentation and functionality evolved.  It's not actually possible to understand all the usages of this library without the README, the documentation, and looking at the unit tests.  That's a real documentation bug.

Initially, this was developed to use the `Get()` method, then `args::get()` was introduced to wallpaper over differences that existed before a major version bump unified them anyway, and then afterward, using the dereference operators (`*var` and `var->inner_value`) were introduced, which I personally prefer, because it better matches the use of `std::optional`.  It's messy that there are three ways to do the same thing, but I didn't remove the other ways to avoid breaking existing code.

The documentation could use a lot of love, and I would prefer if everything was available in one place, but my priorities are elsewhere.  If I were really to start investing time into C++ argument parsing again, it would be in writing a complete replacement to this library in C++20, rather than working on this one.  There are a lot of things about this library that make it hard to work on architecturally, and it reinvents a lot of wheels in some odd ways.  Otherwise, I'm always happy to accept pull requests.
