### ISSUE TITLE
Making it faster (although you shouldn't care)

### ISSUE THREAD

**Issue by gknowles** [Taywee/args#18]
I enjoyed your benchmark, and args was about ~15% faster than dimcli, but when I reduced the loop to just the parse call and asserts it was 30% slower. This is entirely because creating an istringstream object takes a long time, if you did something like make it a member of ValueReader and just call ss.clear(); ss.str(value); for each parse you'll go 20-40% faster overall - yes, it makes that much of a difference.

**Comment by Taywee** [comment]
Yes, you're right.  I mostly threw the benchmark together for fun and out of curiosity rather than to be any legitimately useful information.  As the reader is replaceable, it should be easy enough to do it on a case-by-case basis, but it could be improved in the default reader.

Command line argument parsing efficiency isn't usually that vital, as process startup will absolutely dwarf the amount of time parsing will take, but it can be useful if you are using the library for something else (like passing arguments into a persistent process, like a daemon that parses some CLI-like arguments or a program that presents its own command line).

I've never heard of DIMCLI, but I will definitely check it out now.  I've only created args to be a useful library for my own projects, and if I can find something better, I'll happily retire it and use the better option.  I'm always receptive to better solutions.

**Comment by gknowles** [comment]
I doubt anyone has heard of dimcli :)  Same story though, I couldn't find anything I liked so I wrote it for my own use as part of a larger framework. Then later broke it out into it's own thing mostly to see how hard it would be to productize something.

Command line parsers are far more interface than function, which means what's best is much more a matter of taste than other kinds of libraries.
