### ISSUE TITLE
Multiple definitions during link

### ISSUE THREAD

**Issue by JezhikLaas** [Taywee/args#21]
Hi!
Using the header from multiple source files results in link errors. Are the missing inline statements on purpose or by accident? Great library, thanks for it!

**Comment by Taywee** [comment]
Missing by accident.  I hadn't planned for the possibility of the header being used from multiple translation units, but I probably should have.

**Comment by JezhikLaas** [comment]
Thanks for the quick reply. I made a cmd tool much like the git example with lots of subcommands and I placed every one in its own implementation file, along with its documentation.
Not very unusual, I guess. Adding the inline statements worked just fine.

**Comment by travisdowns** [comment]
Ran into this too, submitted a PR for the fix: adding `inline` to the three non-class functions that had this issue. FWIW `static` would work too but change the semantics a bit. Either one has a somewhat undefined impact on the binary size, `static` conceptually results in at least one copy of the function in each TU that uses, but it may be inlined anyway. `inline` may result in more copies, or fewer (as little as one in the whole final executable). In practice it's not important since the functions are quite small.
