### ISSUE TITLE
Implicit values

### ISSUE THREAD

**Issue by pavel-belikov** [Taywee/args#33]
It would be nice to have implicit values for flags like `-j[N]` in `make`.

I know they are mentioned in readme:

> It will not ever:
> - Allow one value flag to take a specific number of values (like --foo first second, where --foo slurps both arguments). You can instead split that with a flag list (--foo first --foo second) or a custom type extraction ( --foo first,second)
> - Allow you to have value flags only optionally accept values

Is it because of the technical difficulties? I have working implementation, but it requires some incompatible changes in interfaces (`ValueFlagBase::ParseValue` for instance). Usage is simple:

```c++
ImplicitValueFlag<int> foo("foo", "foo", implicitValue, defaultValue);
// or: ImplicitValueFlag<int> foo("foo", "foo", defaultValue);
// or: ImplicitValueFlag<int> foo("foo", "foo");
```

Will you accept such PR?

**Comment by Taywee** [comment]
The main reason I don't like that is because it leaves ambiguities, and makes parsing weird.  For instance, if I have a flag `--foo, -f` which accepts a value, and a flag `--bar, -b` which doesn't, the command line with `-f -b` can be seen as either `-f` taking `-b` as a value or `-f` with its implicit value, and also `-b` as a flag.  It would have to have very specific rules around it, such as flags with implicit values requiring an explicit value not be separated from the flag by a space.

My main reasons in putting that in the "will not ever" section were that I didn't want to hash that out and deal with the messy "the next argument is possibly either the value of this flag or maybe another flag or positional" logic, and also that I don't like that logic in the first place, because it involves a specific kind of flag that takes an argument in a nonstandard way and doesn't behave like the rest, and it makes the presence or absence of that whitespace significant, which I'm not a fan of.  I'm honestly not against this library being able to do that, as it would be optional either way, if it's done in a backwards-compatible and clean way.  A lot of the plumbing of this library is messy enough as it is and could probably use a bit of cleaning up regardless.  So it's 15% ideological and 85% "I just didn't want to do it".

If you made a pull request with an illustrative unit test, and it didn't break any of the existing unit tests, I'd most likely pull it in even with incompatible changes in interfaces, as I mostly only care about a consistent external API.  Even if there were small changes in certain parts of the external API (such as the value reading functors), I'd be fine with it as long as the vast majority of use cases don't break.

**Comment by Taywee** [comment]
So in summary, yes, I would accept such a PR.
