### ISSUE TITLE
Default arguments, ValueFlagList and reset

### ISSUE THREAD

**Issue by UEWiebelitz** [Taywee/args#71]
Hi,

when I initialize a ValueFlagList with default arguments these defaults are reset when parsing the arguments.
Is it possible to circumvent this?

Thanks in advance!

**Comment by Taywee** [comment]
Hm, not at the moment.  With most of the other objects, they store the defaultValue inside of themselves so that when they are reset, they are reassigned the defaultValue.  `ValueFlagList`, on the other hand, simply clears itself on `Reset`.  This is clearly a bug.  I'll see if I can get this corrected soon.

**Comment by UEWiebelitz** [comment]
I already noticed that behavior of other types. They're working great :-)

It would be awesome if there would be a possibility to fix it!

I think it shouldn't be that complicated. If you do not find time for this I could try to make a suggestion based on the correctly working types.

**Comment by Taywee** [comment]
This should be fixed now.  There is a new release (6.2.1) for it.  Let me know if this does what you need it to do.

**Comment by Taywee** [comment]
And to be clear, putting the default value in the list and then adding to the list will do just that, add to the list, rather than replace it.  Different behavior can be achieved by checking the value's own matched status before adding (ie. clearing before adding and setting to matched), but it's unclear what the user would actually want to do in cases like this.  There could be arguments for either side.
And thank you very much for the report.

**Comment by pavel-belikov** [comment]
I was working on the fix also, but @Taywee did it before me. Do you mean that now ValueFlagList's actual value is defaultValues + "valuesAddedByTheUser"? To me it seems inconsistent. Default value should be used when there is no value set by user. You can add some "preset" values after parsing. It seems easier than excluding default ones.

BTW, i noticed that this code compiles: `ValueFlagList<int> ints(parser, "", "", {1, 2})`. I guess, i'll try to forbid these implicit conversions.

**Comment by Taywee** [comment]
@pavel-belikov Yes, you're right.  It does seem somewhat inconsistent.  It treats the defaultValue as something more like a starting value instead.  Perhaps the other specified behavior makes more sense, (changing `values.insert(...` to a `if (*this) { values.clear(); } values.insert(...` or something of the sort).  In many cases the user might want the defaultValue to represent a starting value instead, but the default value case is probably more common.  I'll work on changing this, which should be pretty trivial to change at this point.

**Comment by UEWiebelitz** [comment]
Ah you both are great! :-)
I also expected a replacement of default arguments by user input.

**Comment by pavel-belikov** [comment]
It still seems inconsistent to me, but it's a matter of preference. Either way it should be covered by tests and documentation.

**Comment by Taywee** [comment]
Yeah, that's probably the usual case.  What would fix this is adding an override for Match on all List classes to clear the values on a Match.

**Comment by Taywee** [comment]
I'll get to work on getting this set up and tested.

**Comment by UEWiebelitz** [comment]
Thinking some more minutes about this, pavel-belikov might be right: Default arguments should only be used if no user input is available for the list.
This means a single element given by a user should replace the complete list of default values.

Thanks a lot, guys!

**Comment by Taywee** [comment]
Re-corrected and released.  Now matching an unmatched list argument will clear its value first.

**Comment by UEWiebelitz** [comment]
Works great!
