### ISSUE TITLE
noexcept warning in Visual Studio 2019

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Taywee/args#88]
This kind of function may not throw. Declare it 'noexcept' (f.6).	460	

```            Matcher(std::initializer_list<EitherFlag> in) :
                Matcher(EitherFlag::GetShort(in), EitherFlag::GetLong(in)) {}

            Matcher(Matcher &&other) : shortFlags(std::move(other.shortFlags)), longFlags(std::move(other.longFlags))
```

**Comment by ScottHutchinson** [comment]
We're getting that same warning in VS 2019. Fixed it like this:

```c++
            Matcher(Matcher &&other) noexcept : shortFlags(std::move(other.shortFlags)), longFlags(std::move(other.longFlags))
```

Also getting two Warnings C6330: 'char' passed as _Param_(1) when 'unsigned char' is required in call to 'isspace'.

Fixed by adding `unsigned` in two lines like this (there might be a better fix than this, not sure):
```c++
    for (unsigned char c :
```
Submitted PR https://github.com/Taywee/args/pull/99
