### ISSUE TITLE
Sub group validation not working as expected

### ISSUE THREAD

**Issue by Shielsy** [Taywee/args#90]
I've created a group and a subgroup which has an `AllOrNone` validator (see example below). I expect that I must specify either all `-a -b -c` flags or none as arguments. This is not the case. I can specify one or more. 

```
cpp    args::ArgumentParser parser("This is a test program.", "This goes after the options.");
    args::Group group (parser, "Group:", args::Group::Validators::DontCare);
    args::Group subgroup (group, "SubGroup:", args::Group::Validators::AllOrNone);
    args::Flag aflag(subgroup, "a", "test flag", {'a'});
    args::Flag bflag(subgroup, "b", "test flag", {'b'});
    args::Flag cflag(subgroup, "c", "test flag", {'c'});
```
If I make the make the change below (set subgroup parent as parser), then it works. Is this a bug?

```
cpp    args::ArgumentParser parser("This is a test program.", "This goes after the options.");
    args::Group group (parse, "SubGroup:", args::Group::Validators::AllOrNone);
    args::Flag aflag(subgroup, "a", "test flag", {'a'});
    args::Flag bflag(subgroup, "b", "test flag", {'b'});
    args::Flag cflag(subgroup, "c", "test flag", {'c'});
```

**Comment by Taywee** [comment]
This is expected behavior.  `group` has `DontCare`, meaning "I don't care about the validation of my children".  AllOrNone does fail validation, but group passes validation.  The parser is valid if all its children are.

In this case, you can still manually check the validation of `subgroup`, but it won't throw an error, because the ArgumentParser's children all validate.

**Comment by Shielsy** [comment]
Thanks for the reply. I interpreted `DontCare` differently.

I guess I should have specified `AllChildGroups` instead.
