### ISSUE TITLE
Cannot pass negative values to NargsValueFlag<double> 

### ISSUE THREAD

**Issue by pettitpeon** [Taywee/args#93]
`./Example -a -1.5 2.0`

terminate called after throwing an instance of 'args::ParseError'
  what():  Flag 'a' requires at least one argument but received none
Aborted

**Comment by Taywee** [comment]
This is definitely a bug.  This appears to happen inside [ParseArgsValues](https://github.com/Taywee/args/blob/84c7f36ee123aaea0dd6653204435e473f1b088e/args.hxx#L2321) at [this point](https://github.com/Taywee/args/blob/84c7f36ee123aaea0dd6653204435e473f1b088e/args.hxx#L2352-L2354) because it checks if the argument has the short or long prefix to be a flag. if nargs.min != nargs.max.  This should probably instead only check `size < nargs.min`, but it still will fail on ambiguous cases (such as if `-a` needs 1 or 2 arguments, but the second argument is negative, in which case there's no unambiguous and reasonable way for the library to determine whether it is supposed to be a negative number or a short flag with a digit character.  It would be potentially possible to try to match against all flags again, but that's messy, and would cause exsiting use of your programs to break if you happen to add a digit flag that somebody else is using, not to mention if the program is used dynamically, it might sometimes work and sometimes not depending on the ambiguity of the digit, and might sometimes even silently do the wrong thing).

**Comment by Taywee** [comment]
This is fixed with version 6.2.4

Note that this will still fail if you specify a negative value (which has the same prefix as the short flags) when you're over the Narg minimum threshold.  This is intentional for the reasons stated above.  So for your example, if your `-a` flag is Narg {1, 2}, the second value will not be able to be negative, because adding the digit flag later would cause a failure.  Nargs with variable value counts already cause ambiguity quite easily, so that particular case won't be workshopped.  You can fully avoid this by using a ValueFlagList or PositionalList.

**Comment by pettitpeon** [comment]
Thanks man! I will update to 6.2.4
Cheers
